// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Nm2r7bUvEsXMzVG8arHox6-v0o9--Cc',
    appId: '1:745940894687:web:5b5207f71ffa2931b07a6a',
    messagingSenderId: '745940894687',
    projectId: 'tdpmain-82b09',
    authDomain: 'tdpmain-82b09.firebaseapp.com',
    storageBucket: 'tdpmain-82b09.appspot.com',
    measurementId: 'G-31T42FWPP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOtbTJstDapCqO_B0CpbyjKIqMoQATAgs',
    appId: '1:745940894687:android:c672f3da1aab73c2b07a6a',
    messagingSenderId: '745940894687',
    projectId: 'tdpmain-82b09',
    storageBucket: 'tdpmain-82b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKZN2XT3f2Gj7qOPHLesce1dEj3-vYZ84',
    appId: '1:745940894687:ios:d946281f250f269eb07a6a',
    messagingSenderId: '745940894687',
    projectId: 'tdpmain-82b09',
    storageBucket: 'tdpmain-82b09.appspot.com',
    iosBundleId: 'com.example.usertdpone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKZN2XT3f2Gj7qOPHLesce1dEj3-vYZ84',
    appId: '1:745940894687:ios:a29618a337e9a547b07a6a',
    messagingSenderId: '745940894687',
    projectId: 'tdpmain-82b09',
    storageBucket: 'tdpmain-82b09.appspot.com',
    iosBundleId: 'com.example.usertdpone.RunnerTests',
  );
}
