// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg5y9HX9_rW9rkLrDYQ70K7VtEWMif7ZE',
    appId: '1:77398095267:web:729ce8a5aa98d7d8ed5616',
    messagingSenderId: '77398095267',
    projectId: 'ysrcp-584dc',
    authDomain: 'ysrcp-584dc.firebaseapp.com',
    storageBucket: 'ysrcp-584dc.appspot.com',
    measurementId: 'G-CCC91G785K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4aFpxdLbyBRUCDF6cL82zI2_Rz25-sY',
    appId: '1:77398095267:android:4dbde5959a7ed671ed5616',
    messagingSenderId: '77398095267',
    projectId: 'ysrcp-584dc',
    storageBucket: 'ysrcp-584dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVs_piuFkeU_hkBNRcO3LtxNXDzhyVORk',
    appId: '1:77398095267:ios:c360a13e30e1d07ced5616',
    messagingSenderId: '77398095267',
    projectId: 'ysrcp-584dc',
    storageBucket: 'ysrcp-584dc.appspot.com',
    iosBundleId: 'com.example.userysrcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVs_piuFkeU_hkBNRcO3LtxNXDzhyVORk',
    appId: '1:77398095267:ios:5ef4331454bb3504ed5616',
    messagingSenderId: '77398095267',
    projectId: 'ysrcp-584dc',
    storageBucket: 'ysrcp-584dc.appspot.com',
    iosBundleId: 'com.example.userysrcp.RunnerTests',
  );
}
